<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Samays-MacBook-Air.local" failures="1" tests="1" name="Command line test" time="0.088" errors="0" timestamp="25 Jul 2021 19:45:11 GMT">
  <testcase classname="coindcxtest.coindcxtest.LoginTest" name="login" time="0.05">
    <failure type="java.lang.AssertionError" message="expected [10] but found [20]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [20]
	at coindcxtest.coindcxtest.LoginTest.login(LoginTest.java:15)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Command line test -->
